name: Run Spectral on Pull Requests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Run Spectral
      - uses: stoplightio/spectral-action@v0.7.3
        with:
          file_glob: 'doc/api/*.yaml'
          spectral_ruleset: .spectral.yaml
